language: node_js
node_js:
  - "10"

cache: yarn

script: yarn run build

deploy:
  provider: pages
  repo: asmadsen/asmadsen.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
